### ISSUE TITLE
@conda-forge-admin, please add user MementoRC

### ISSUE THREAD

**Issue by MementoRC** [conda-forge/eth-account-feedstock#22]

**Comment by step21** [comment]
Please show some contribution first. There are good reasons why this pkg isn’t updated. If you can fix those, like building the necessary additional pkg properly, then I can add you.

**Comment by MementoRC** [comment]
Good point, I thought it wasn't maintained. I'll give it a try, I need the 0.12.1 for another recipe. Thx

**Comment by step21** [comment]
Yeah, sorry about that. You can find my pre existing work and discussions with conda-forge reviewers here: https://github.com/conda-forge/staged-recipes/pull/26068
My biggest issue is that they would like it to either use only clang or only gcc on all platforms.
